FROM        scratch
MAINTAINER  Paul Ward <pward123@gmail.com>
ADD         rootfs.tar /

#RUN         npm install -g wait-for-mongo

# Setup the environment
#ENV         PORT 80
#ENV         ROOT_URL http://127.0.0.1
#ENV         MONGO_URL mongodb://mongo:27017/meteor
#ENV         MONGO_OPLOG_URL mongodb://mongo:27017/local
